[package]
name = "ic"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.30", features = ["derive"] }
image = "0.25.5"
indicatif = "0.17.11"

[profile.release]
lto = true
codegen-units = 1
strip = true
panic = "abort"
opt-level = "z"